Flowpack:
  ElasticSearch:
    indexes:
      default:
        neoscr:
          settings:
            index:
              number_of_shards: 1
              number_of_replicas: 0
              default_pipeline: _none
